name: Trigger Automation Tests

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tests in project-automation
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/dixithimanshu28ind/project-automation/dispatches \
          -d '{"event_type": "run-tests"}'
